#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]


def replace(path: str, old: str, new: str) -> None:
    p = ROOT / path
    text = p.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"Expected block not found in {path}: {old[:180]!r}")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")


def integrate_generated_font(generated: Path) -> None:
    if not generated.is_file():
        raise SystemExit(f"Generated CPHUN-85 font not found: {generated}")
    text = generated.read_text(encoding="utf-8")
    if "notoserif_14_regular_unicode" not in text:
        raise SystemExit("Unexpected generated font symbols")
    text = text.replace("notoserif_14_regular_unicode", "notoserif_14_regular")
    marker = "/**\n * generated by fontconvert.py"
    replacement = "/**\n * CPHUN-85 dictionary Unicode edition: 1325/1333 dictionary non-ASCII codepoints.\n * Embedded by CPHUN-86 as the built-in Noto Serif 14 pt Regular face.\n * generated by fontconvert.py"
    if marker not in text:
        raise SystemExit("Generated font header marker not found")
    text = text.replace(marker, replacement, 1)
    (ROOT / "lib/EpdFont/builtinFonts/notoserif_14_regular.h").write_text(text, encoding="utf-8")


def patch_dictionary_activity() -> None:
    old = """// Dictionary definitions always use the built-in Noto Serif family so glyph
// availability never depends on the selected reading font or an SD-card font.
// Noto Serif renders visibly larger than most alternative reader fonts at the
// same nominal point size on this display. For non-Noto-Serif reader fonts,
// apply a calibrated -2 pt optical correction before selecting the nearest
// built-in Noto Serif size. Built-in Noto Serif keeps its native size.
int dictionaryBodyFontId() {
  int visualSize = SETTINGS.fontPointSize;
  const bool readerIsBuiltInNotoSerif =
      SETTINGS.sdFontFamilyName[0] == '\\0' && SETTINGS.fontFamily == CrossPointSettings::NOTOSERIF;
  if (!readerIsBuiltInNotoSerif) visualSize = std::max(12, visualSize - 2);
  if (visualSize <= 13) return NOTOSERIF_12_FONT_ID;
  if (visualSize <= 15) return NOTOSERIF_14_FONT_ID;
  if (visualSize <= 17) return NOTOSERIF_16_FONT_ID;
  return NOTOSERIF_18_FONT_ID;
}
"""
    new = """// Dictionary definition body is intentionally fixed at Noto Serif 14 pt
// Regular. Missing glyphs in any font/style used while the dictionary is open
// are rendered character-by-character from the expanded 14 pt Regular face.
int dictionaryBodyFontId() { return NOTOSERIF_14_FONT_ID; }
"""
    replace("src/activities/reader/DictionaryDefinitionActivity.cpp", old, new)

    replace(
        "src/activities/reader/DictionaryDefinitionActivity.cpp",
        """void DictionaryDefinitionActivity::onEnter() {
  Activity::onEnter();
  // Normalize StarDict multi-type separators so the wrap loop and the
""",
        """void DictionaryDefinitionActivity::onEnter() {
  Activity::onEnter();
  // CPHUN-86: enable render-only, per-glyph fallback for the complete
  // dictionary activity (plain text, styled HTML, source lines and headings).
  renderer.setMissingGlyphFallbackFont(NOTOSERIF_14_FONT_ID);
  // Normalize StarDict multi-type separators so the wrap loop and the
""",
    )

    replace(
        "src/activities/reader/DictionaryDefinitionActivity.cpp",
        """void DictionaryDefinitionActivity::onExit() {
  Activity::onExit();
  if (auto* fcm = renderer.getFontCacheManager()) {
""",
        """void DictionaryDefinitionActivity::onExit() {
  renderer.clearMissingGlyphFallbackFont();
  Activity::onExit();
  if (auto* fcm = renderer.getFontCacheManager()) {
""",
    )


def patch_renderer_header() -> None:
    replace(
        "lib/GfxRenderer/GfxRenderer.h",
        """  std::map<int, int> fallbackFontMap_;

  // If `text` contains a CJK codepoint that `fontId` cannot render and `fontId`
""",
        """  std::map<int, int> fallbackFontMap_;

  // Optional render-only fallback used by the dictionary. Unlike the CJK UI
  // fallback above, this is character-by-character: the requested font/style
  // remains untouched for every glyph it owns, and only a missing glyph is
  // rendered with REGULAR from this font id. Measurements intentionally stay
  // on the requested font for the first CPHUN-86 iteration.
  int missingGlyphFallbackFontId_ = 0;

  // If `text` contains a CJK codepoint that `fontId` cannot render and `fontId`
""",
    )

    replace(
        "lib/GfxRenderer/GfxRenderer.h",
        """  void clearFallbackFonts() { fallbackFontMap_.clear(); }
  // Ensure SD card font glyph data is loaded for the given text. Called from layout code
""",
        """  void clearFallbackFonts() { fallbackFontMap_.clear(); }
  // Render-only per-glyph fallback. A value of 0 disables it. This is scoped
  // by DictionaryDefinitionActivity so normal reader/UI rendering is unchanged.
  void setMissingGlyphFallbackFont(int fontId) { missingGlyphFallbackFontId_ = fontId; }
  void clearMissingGlyphFallbackFont() { missingGlyphFallbackFontId_ = 0; }
  // Ensure SD card font glyph data is loaded for the given text. Called from layout code
""",
    )


def patch_renderer_cpp() -> None:
    replace(
        "lib/GfxRenderer/GfxRenderer.cpp",
        """  if (fontCacheManager_ && fontCacheManager_->isScanning()) {
    fontCacheManager_->recordText(renderedText, resolvedFontId, style);
    return;
  }

  // Redirected to the SD fallback: batch-load the string's glyphs so the draw
""",
        """  if (fontCacheManager_ && fontCacheManager_->isScanning()) {
    fontCacheManager_->recordText(renderedText, resolvedFontId, style);
    // Prewarm the regular fallback face as a second style/font group. Recording
    // the full rendered string is deliberate: recordText de-duplicates
    // codepoints and this guarantees compressed fallback bitmaps are resident
    // before the paint pass without changing measurement/layout.
    if (missingGlyphFallbackFontId_ != 0 &&
        (missingGlyphFallbackFontId_ != resolvedFontId || style != EpdFontFamily::REGULAR)) {
      fontCacheManager_->recordText(renderedText, missingGlyphFallbackFontId_, EpdFontFamily::REGULAR);
    }
    return;
  }

  // Redirected to the SD fallback: batch-load the string's glyphs so the draw
""",
    )

    replace(
        "lib/GfxRenderer/GfxRenderer.cpp",
        """  const auto& font = fontIt->second;

  const char* textCursor = renderedText;
""",
        """  const auto& font = fontIt->second;
  const EpdFontFamily* missingGlyphFallback = nullptr;
  if (missingGlyphFallbackFontId_ != 0) {
    const auto fallbackIt = fontMap.find(missingGlyphFallbackFontId_);
    if (fallbackIt != fontMap.end()) {
      missingGlyphFallback = &fallbackIt->second;
    }
  }

  const char* textCursor = renderedText;
""",
    )

    replace(
        "lib/GfxRenderer/GfxRenderer.cpp",
        """    if (utf8IsCombiningMark(cp) || BidiUtils::isTransparentMark(cp)) {
      const EpdGlyph* combiningGlyph = font.getGlyph(cp, style);
      if (!combiningGlyph) continue;
      const auto anchor = combiningMark::anchorFor(cp);
      const int raiseBy =
          combiningMark::raiseAboveBase(anchor, combiningGlyph->top, combiningGlyph->height, lastBaseTop);
      const int combiningX = combiningMark::anchorOver(anchor, lastBaseX, lastBaseLeft, lastBaseWidth,
                                                       combiningGlyph->left, combiningGlyph->width);
      renderCharImpl<TextRotation::None>(*this, renderMode, font, cp, combiningX, yPos - raiseBy, black, style);
      continue;
    }
""",
        """    if (utf8IsCombiningMark(cp) || BidiUtils::isTransparentMark(cp)) {
      const EpdFontFamily* combiningFont = &font;
      EpdFontFamily::Style combiningStyle = style;
      const EpdGlyph* combiningGlyph = font.getGlyph(cp, style);
      if (!combiningGlyph && missingGlyphFallback != nullptr) {
        combiningGlyph = missingGlyphFallback->getGlyph(cp, EpdFontFamily::REGULAR);
        if (combiningGlyph) {
          combiningFont = missingGlyphFallback;
          combiningStyle = EpdFontFamily::REGULAR;
        }
      }
      if (!combiningGlyph) continue;
      const auto anchor = combiningMark::anchorFor(cp);
      const int raiseBy =
          combiningMark::raiseAboveBase(anchor, combiningGlyph->top, combiningGlyph->height, lastBaseTop);
      const int combiningX = combiningMark::anchorOver(anchor, lastBaseX, lastBaseLeft, lastBaseWidth,
                                                       combiningGlyph->left, combiningGlyph->width);
      renderCharImpl<TextRotation::None>(*this, renderMode, *combiningFont, cp, combiningX, yPos - raiseBy, black,
                                         combiningStyle);
      continue;
    }
""",
    )

    replace(
        "lib/GfxRenderer/GfxRenderer.cpp",
        """    const EpdGlyph* glyph = font.getGlyph(cp, style);

    lastBaseLeft = glyph ? glyph->left : 0;
    lastBaseWidth = glyph ? glyph->width : 0;
    lastBaseTop = glyph ? glyph->top : 0;
    prevAdvanceFP = glyph ? glyph->advanceX : 0;  // 12.4 fixed-point

    const bool isSupSub = (style & (EpdFontFamily::SUP | EpdFontFamily::SUB)) != 0;
    if (isSupSub) {
      // Halve the advance so the cursor advances by the same amount the scaled glyph
      // actually occupies, keeping spacing correct without needing a separate smaller font.
      prevAdvanceFP = (prevAdvanceFP + 1) / 2;
    }

    if (isSupSub) {
      // yPos already carries the vertical offset applied by TextBlock::render().
      renderCharScaled(*this, renderMode, font, cp, lastBaseX, yPos, black, style);
    } else {
      renderCharImpl<TextRotation::None>(*this, renderMode, font, cp, lastBaseX, yPos, black, style);
    }
    prevCp = cp;
""",
        """    const EpdFontFamily* glyphFont = &font;
    EpdFontFamily::Style glyphStyle = style;
    const EpdGlyph* glyph = font.getGlyph(cp, style);
    bool usingMissingGlyphFallback = false;
    if (!glyph && missingGlyphFallback != nullptr) {
      glyph = missingGlyphFallback->getGlyph(cp, EpdFontFamily::REGULAR);
      if (glyph) {
        glyphFont = missingGlyphFallback;
        glyphStyle = EpdFontFamily::REGULAR;
        usingMissingGlyphFallback = true;
      }
    }

    lastBaseLeft = glyph ? glyph->left : 0;
    lastBaseWidth = glyph ? glyph->width : 0;
    lastBaseTop = glyph ? glyph->top : 0;
    prevAdvanceFP = glyph ? glyph->advanceX : 0;  // 12.4 fixed-point

    // The fallback is deliberately the literal 14 pt Regular glyph, even when
    // the missing source glyph was bold/italic/sup/sub. Only native glyphs keep
    // the requested SUP/SUB half-scale treatment.
    const bool isSupSub = !usingMissingGlyphFallback && (style & (EpdFontFamily::SUP | EpdFontFamily::SUB)) != 0;
    if (isSupSub) {
      // Halve the advance so the cursor advances by the same amount the scaled glyph
      // actually occupies, keeping spacing correct without needing a separate smaller font.
      prevAdvanceFP = (prevAdvanceFP + 1) / 2;
    }

    if (isSupSub) {
      // yPos already carries the vertical offset applied by TextBlock::render().
      renderCharScaled(*this, renderMode, *glyphFont, cp, lastBaseX, yPos, black, glyphStyle);
    } else {
      renderCharImpl<TextRotation::None>(*this, renderMode, *glyphFont, cp, lastBaseX, yPos, black, glyphStyle);
    }
    prevCp = cp;
""",
    )


def patch_build_id() -> None:
    replace(
        "src/CPHUNBuildId.h",
        '#define CPHUN_BUILD_ID "CPHUN-260909-84"',
        '#define CPHUN_BUILD_ID "CPHUN-260910-86"',
    )


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: cphun86_dictionary_unicode_patch.py <generated-font-header>")
    integrate_generated_font(Path(sys.argv[1]))
    patch_dictionary_activity()
    patch_renderer_header()
    patch_renderer_cpp()
    patch_build_id()
    print("CPHUN-86 dictionary Unicode integration applied")


if __name__ == "__main__":
    main()
