from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"Expected one match in {path}, found {count}")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")


replace_once("src/CPHUNBuildId.h", "CPHUN-260910-90", "CPHUN-260910-91")

path = "src/activities/reader/DictionaryWordSelectActivity.cpp"
old = '''    // Restore a hyphenated orthographic unit from hidden punctuation tokens.\n    const WordBox& current = words[selected];\n    if (current.block) {\n      const TextBlock* block = current.block;\n      int start = current.tokenIndex;\n      int end = current.tokenIndex;\n      if (start >= 2 && isExplicitHyphenToken(block->wordText(start - 1)) &&\n          isSelectableToken(block->wordText(start - 2)))\n        start -= 2;\n      if (end + 2 < block->wordCount() && isExplicitHyphenToken(block->wordText(end + 1)) &&\n          isSelectableToken(block->wordText(end + 2)))\n        end += 2;\n      if (start != end) {\n        std::string compound;\n        for (int i = start; i <= end; ++i) compound += block->wordText(i);\n        appendUnique(candidates, std::move(compound));\n      }\n    }\n'''
new = '''    // Restore a hyphenated orthographic unit from hidden punctuation tokens.\n    // Same-line compounds stay inside one TextBlock. CPHUN-91 additionally\n    // bridges an explicit hyphen at a rendered line/TextBlock boundary, so a\n    // lexical unit such as `Márvány-tenger` remains searchable even when the\n    // reader wraps immediately after the visible hyphen. The bridge is strict:\n    // no ordinary neighbouring words are ever concatenated.\n    const WordBox& current = words[selected];\n    if (current.block) {\n      const TextBlock* block = current.block;\n      int start = current.tokenIndex;\n      int end = current.tokenIndex;\n      if (start >= 2 && isExplicitHyphenToken(block->wordText(start - 1)) &&\n          isSelectableToken(block->wordText(start - 2)))\n        start -= 2;\n      if (end + 2 < block->wordCount() && isExplicitHyphenToken(block->wordText(end + 1)) &&\n          isSelectableToken(block->wordText(end + 2)))\n        end += 2;\n      if (start != end) {\n        std::string compound;\n        for (int i = start; i <= end; ++i) compound += block->wordText(i);\n        appendUnique(candidates, std::move(compound));\n      }\n\n      // Selected right half on the first token of a new rendered line:\n      // previous selectable word + explicit hyphen at previous block end + current.\n      if (current.tokenIndex == 0 && selected > 0) {\n        const WordBox& previous = words[selected - 1];\n        if (previous.block && previous.block != block && previous.row + 1 == current.row &&\n            previous.block->wordCount() >= 2) {\n          const uint16_t hyphenIndex = previous.block->wordCount() - 1;\n          if (previous.tokenIndex + 1 == hyphenIndex &&\n              isExplicitHyphenToken(previous.block->wordText(hyphenIndex))) {\n            std::string compound = previous.text;\n            compound += previous.block->wordText(hyphenIndex);\n            compound += current.text;\n            appendUnique(candidates, std::move(compound));\n          }\n        }\n      }\n\n      // Selected left half immediately before an explicit hyphen that ends the\n      // rendered line: current + hyphen + first selectable token of next line.\n      if (selected + 1 < static_cast<int>(words.size()) && block->wordCount() >= 2 &&\n          current.tokenIndex + 1 == block->wordCount() - 1 &&\n          isExplicitHyphenToken(block->wordText(block->wordCount() - 1))) {\n        const WordBox& next = words[selected + 1];\n        if (next.block && next.block != block && next.row == current.row + 1 && next.tokenIndex == 0) {\n          std::string compound = current.text;\n          compound += block->wordText(block->wordCount() - 1);\n          compound += next.text;\n          appendUnique(candidates, std::move(compound));\n        }\n      }\n    }\n'''
replace_once(path, old, new)
